name 'sentry'
maintainer 'Openhood S.E.N.C'
maintainer_email 'jonathan@openhood.com'
license 'Apache 2.0'
description 'Installs/Configures Sentry - A realtime error logging and aggregation platform.'
long_description 'Installs/Configures Sentry - A realtime error logging and aggregation platform.'
version '1.0.0'

supports 'ubuntu', '>= 12.04'
supports 'redhat', '>= 6.7'
supports 'centos', '>= 6.7'

depends 'poise'
depends 'poise-service'
depends 'poise-python'
